# Generated by Django 4.1.5 on 2023-02-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=350)),
                ("good_counts", models.PositiveIntegerField()),
                (
                    "people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="people.people",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="boards", to="subjects.subject"
                    ),
                ),
            ],
        ),
    ]
