# Generated by Django 4.1.5 on 2023-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "image"), ("video", "video")], max_length=10
                    ),
                ),
            ],
        ),
    ]
