version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=database-2.cc2w5bux6qbo.ap-northeast-2.rds.amazonaws.com
      - DB_NAME=django
      - DB_USER=adminadmin
      - DB_PASS=adminadmin
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=database-2.cc2w5bux6qbo.ap-northeast-2.rds.amazonaws.com
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=adminadmin
