# Generated by Django 4.1.5 on 2023-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("follow_count", models.PositiveIntegerField()),
                ("profile_thumbnail_url", models.ImageField(upload_to="")),
            ],
        ),
    ]
