# Generated by Django 4.1.5 on 2023-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("page", models.PositiveIntegerField()),
                (
                    "boards",
                    models.ManyToManyField(related_name="clone", to="boards.board"),
                ),
            ],
        ),
    ]
